### ISSUE TITLE
Angular-Flickity does not properly initialize using the directive inside Angular-UI-Router's UI-View

### ISSUE THREAD

**Issue by zurie** [benjamincharity/angular-flickity#30]
Using Angular 1.5 / Angular-UI Router 0.2.x

Similar to this issue here:
[https://github.com/metafizzy/flickity-docs/issues/4](https://github.com/metafizzy/flickity-docs/issues/4)

When initializing Flickity using native javascript / jquery the gallery inits correctly, but allowing the directive to do the initialization, the gallery is stacked vertically on top of itself and no functionality is working.

This only happens inside a Angular-UI Routers "UI-View" that is pulling in a "templateURL"  if you move the directive outside the UI-View it works or if you alternatively define a inline template with UI-Router, it works.

A workaround was for me to initialize the gallery with the Service inside of the corresponding Controller of my UI-View.

```
$timeout(function() {
	FlickityService.create('.demo__slides', $scope.flickityId, $scope.flickityOptions)
},0);
```

[Working CodePen with INLINE template and UI-Router](http://codepen.io/Zuriel/pen/dMRooM)
 i don't have a way to make a codepen with a external template to show it not working.

**Comment by benjamincharity** [comment]
Thanks for the report @zurie. Definitely want to make sure this is as easy to use as the original Flickity library.

I finally got a chance today to actually look into this one. It seems to be the age-old issue of trying to access the DOM before it is fully created. So we have two basic solutions... 

- **a)** wrap the service call inside a `$timeout`
- **b)** wrap the service call inside a `document.ready`

I thought about adding that wrapper inside each method as a safety net of sorts for users. But ultimately this is not really an issue with this module (imo) rather than how it's implemented inside the Angular framework. No matter what we are trying to do from an Angular controller, we will be facing this issue. I believe that using the service on a view controlled by UI-Router simply exacerbated the issue due to fetching the template.

The Angular Way:tm: of doing this would be to create a small directive that simply wraps your slider template and gives you access to `element` which you could use without worrying about the DOM not yet existing. (you could almost just copy the [included directive](https://github.com/benjamincharity/angular-flickity/blob/master/src/flickity.directive.js) with a few adjustments)

- - -

Demo showing it working inside a UI-Router view with an external template using `document.ready`: 

http://embed.plnkr.co/We7brl/

(page 2 shows it not working when not using `document.ready`)

- - -

I am closing for now as I don't see any action needed. Please, feel free to continue this conversation here if you disagree!

**Comment by benjamincharity** [comment]
And I forgot the most important part... I updated the docs to call out this caveat in the hopes of saving anyone else the frustration you faced: https://github.com/benjamincharity/angular-flickity#create

I would love to know if you believe this addition and demo would have been enough to save you from thrashing around on this.

Thanks again @zurie!

**Comment by zurie** [comment]
thanks @benjamincharity.  I think the doc is enough to demonstrate the issue and will be enough to show other users what to do in that specific solution. this isn't the first time i've had to wait for angular before doing things with other javascript libraries.  If your instructions were in the doc it would have helped me out from the get go so I think thats a great addition to the docs for new users.    Thanks again for your work.
