### ISSUE TITLE
index/$timeout in destroy w/ remote calls

### ISSUE THREAD

**Issue by lukebilger** [benjamincharity/angular-flickity#49]
I read #39 and tried that approach.  I have an interactive search that returns items with images. Based on the map drag or filters changed, results could have common items.  So, I had to destroy instances in order to recreate them since their id would be the same.   Because of $timeout in FlickityService.destroy, the destroy was happening after the next create cycle from the next api call, which was making flicketyIndex be outdated since the next create cycle added more instances and the array splicing eventually changed the order of the array causing errors.

I tried to remedy with promises and such but it was getting difficult with all the create and destroy promises happening at different times.

I changed the destroy code to be this to see how it functions (I moved index get inside promise and removed $timeout). 

    value: function destroy(id) {
        var _this2 = this;

        return this.$q(function (resolve, reject) {

            var flickityIndex = _this2._getFlickityIndex(id);

            if (flickityIndex < 0 || !_this2.instances[flickityIndex]) {
                reject('Instance ' + id + ' not found');
            }

            // Destroy the Flickity instance
            _this2.instances[flickityIndex].instance.destroy();

            // Remove the instance from the array
            _this2.instances.splice(flickityIndex, 1);

            resolve('Instance ' + id + ' destroyed.');
        });
    }

With this change, I'm simply using your directive inside the results/ng-repeat and letting angular control the init/destroy lifecycle when the scope changes.  So far its working very well.

I know you had a reason for $timeout in destroy but wanted to make you aware of this edge case and the problems that $timeout was causing with the instances array.

I also think the getFlicketyIndex should be inside the promise, right before the destroy in case the array order changes.

**Comment by benjamincharity** [comment]
Hey @lukebilger, thanks for posting this. I'll be honest, dynamically updating data in the slider wasn't something I thought much about when writing this since the original library didn't seem to think about it either. But it does seem to be a consistent pain point for people so I would like to smooth out all these edge cases.

> I also think the getFlicketyIndex should be inside the promise, right before the destroy in case the array order changes.

This is an easy change with no downside 👍 

I will also do some testing around removing the `$timeout` to see how that affects any other areas of the module. It was [originally introduced](https://github.com/benjamincharity/angular-flickity/commit/a50475517cb53e398a5aa1f1a2eeeb3fa36be3d6) to solve an issue when using a Flickity instance inside of a [ui-router](https://github.com/angular-ui/ui-router) view. I'm sure that we can find a way to get around that issue in a way that serves both cases.

I'll try to put some time towards this early this week.

**Comment by benjamincharity** [comment]
Several issues with promises and timing have been fixed during the upgrade to v2: https://github.com/benjamincharity/angular-flickity/pull/51
