### ISSUE TITLE
With NgAnimate - Flickity is destroyed to early on leave

### ISSUE THREAD

**Issue by adrienlamotte** [benjamincharity/angular-flickity#81]
Hi ! :-)

I'm using AngularJS & NgAnimate 1.6.3, and UI Router. When the route change, the Flickity slider is destroy immediatly, not waiting for the animation leave is ended.
You can try it here : http://plnkr.co/edit/OEkYWrdSEIpRhOhojdWn?p=preview

Any idea on how to solve this ? 

And thank you for your work !

**Comment by benjamincharity** [comment]
Hey there!

This is a tough one... We are currently using the `$scope` [$destroy event](https://github.com/benjamincharity/angular-flickity/blob/master/src/flickity.directive.js#L71-L74) to tear down the Flickity instance. We could listen for events from the router rather than the destroy event, but then it would _only_ be destroyed on a routing event. 

The first solution that comes to mind would be to use the `FlickityService` to create/destroy the slider yourself. Then you could listen for routing events and tear it down yourself. [`FlickityService` example](http://codepen.io/benjamincharity/pen/NRVLEb)

Is that a possible solution for you?

---

(I'm open to other's ideas on how to support both options - but it wouldn't be an immediate fix due to my current workload :/ )

**Comment by adrienlamotte** [comment]
Hi, thanks for taking time to answer :)

I just tried using `FlickityService`, and it works fine! The hard part was to find a way to listen the end of the leave animation... I found a way using the `$animate` service : 
```
$animate.on('leave', angular.element('.your-view-elmt'), function(element, phase) {
    if(phase === "close"){
        FlickityService.destroy("sliderId");
    }
});
```

I don't know if it will be possible to automate that to make it work without using create/destroy services each time ?

Anyway, thank for your time :)

**Comment by benjamincharity** [comment]
I think we may be stuck with manually creating/destroying for now.

To generalize it a bit you could use the `getAll` service method so you could get all instances. Then loop through destroying them. That way you don't have to track specific IDs.

**Comment by benjamincharity** [comment]
test #2
