### ISSUE TITLE
Any plans for Angular 4

### ISSUE THREAD

**Issue by spotonconnect** [benjamincharity/angular-flickity#83]
Any plans for updating to Angular 4?
https://angular.io/

**Comment by benjamincharity** [comment]
Unfortunately, no 😞 

I originally chose the Flickity library because of it's features and because I'm a fan of the creator - not because it works very well with Angular. Flickity is pretty heavy into direct DOM manipulation (which makes sense as it's not technically for use with any framework). So it's really built from a completely different mindset than AngularJS is (where the DOM is simply a representation of the model).

If/when I create another slider wrapper for Angular I'll be looking for one that is based off of an object/array so that the Angular framework can have better control.

---

I haven't actually used this anywhere, but I was looking at [ngx-siema](https://github.com/LexZhukov/ngx-siema). It looks pretty good though so you may want to give it a go.
