### ISSUE TITLE
ng-repeat and push to array

### ISSUE THREAD

**Issue by BrkCoder** [benjamincharity/angular-flickity#90]
Hey I am trying using ng-repeat with angular-flickity.
I am using ng-repeat on 3 elements, I want to push a dynamic item every 30 seconds,
the problem is that when I push an element to the array, the carousel get stuck and not reflect the current state of items in the ng-repeat.
The solution that I found is:
1.Destroy current carousel using FlickityService.
2.Push new elements to array.
3.Recreate the carousel using FlickityService.
The problem with the above workaround is that it is very clanky and demand destruction of DOM elements and recreating it over and over again-very expensive solution.
I have simulate this problem with current codepen:
https://codepen.io/Barak/pen/ayKEba

The optimal solution in my opinion , is that flickity will get update instantly when I update my current array.

I would be happy for any kind of help.

**Comment by benjamincharity** [comment]
Hey @BrkCoder, unfortunately this is where you see the limitations of the actual Flickity library.

I originally chose the Flickity library because of it's features and because I'm a fan of the creator - not because it works very well with Angular. Flickity is pretty heavy into direct DOM manipulation (which makes sense as it's not technically for use with any framework). So it's really built from a completely different mindset than AngularJS is (where the DOM is simply a representation of the model).

Flickity exposes methods to add the item directly into the DOM but this is outside of the AnguarJS detection cycle, plus detection wouldn't really work backwards - adding the injected element to the model that ng-repeat is building from.

You may have more luck using Flickity directly or looking for a slider that is built off of the model rather than the DOM. If/when I create another slider wrapper for Angular, I'll be looking for one like that.

**Comment by benjamincharity** [comment]
Can't fix 😞
